---

- name: Creating minio Serivce
  template:
    src: service.j2
    dest: /etc/systemd/system/minio.service

- name: Starting minio Service
  systemd:
    name: minio
    state: started
    enabled: true
    daemon_reload: true
